### ISSUE TITLE
yolov3.py报错：IndexError: list index out of range

### ISSUE THREAD

**Issue by 1zzc** [wuhanstudio/adversarial-detection#1]
(61384) wsgi starting up on http://0.0.0.0:9090
[[[81, 82], [135, 169], [344, 319]], [[10, 14], [23, 27], [37, 58]]] anchors 0 anchor_i anchors[anchor_i] [[81, 82], [135, 169], [344, 319]]
[[[81, 82], [135, 169], [344, 319]], [[10, 14], [23, 27], [37, 58]]] anchors 1 anchor_i anchors[anchor_i] [[10, 14], [23, 27], [37, 58]]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\adversarial-detection\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\adversarial-detection\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "detect_img.py", line 138, in adversarial_detection_thread
    boxes, class_ids, confidences = yolo_process_output(outs, yolov3_tiny_anchors, len(classes))
  File "D:\allCode\code\adversarial-detection-master\adversarial-detection-master\yolov3.py", line 130, in yolo_process_output
    print(anchors,'anchors',anchor_i,'anchor_i','anchors[anchor_i]',anchors[anchor_i])
IndexError: list index out of range
博主您好，使用Yolov3.h5权重之后出现越界错误

**Comment by wuhanstudio** [comment]
你好，默认是用的 yolo-tiny，

如果是 YOLO，把这一行 anchor 改一下就可以了：

https://github.com/wuhanstudio/adversarial-detection/blob/cc0d070d148a2dfb90a0aec7494061ef1a2cfaed/detect.py#L142

改成：
```
 boxes, class_ids, confidences = yolo_process_output(outs, yolov3_anchors, len(classes))
```

**Comment by 1zzc** [comment]
这是来自QQ邮箱的假期自动回复邮件。  大佬，您好。您的邮件我已收到。                                    --------ZhouZhongChen
